# Numpy Module

In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape # 1차원 arr로 3개의 데이터 가짐

(3,)

In [6]:
arr2=np.array([[1,2,3],
             [2,3,4]])

In [7]:
type(arr2)

numpy.ndarray

In [8]:
arr2.shape # 2차원 arr로 3개의 데이터 가짐 

(2, 3)

In [9]:
# 각 arr의 차원 보기 : ndim 
arr1.ndim

1

In [10]:
arr2.ndim

2

In [11]:
list1=[1,2,3]
type(list1)

list

## list 와 ndarray의 차이점
- list : 서로 다른 데이터 타입 갖는거 가능
- ndarray : 연산 특성 상 같은 데이터 타입만 가능

In [12]:
# 서로 다른 데이터 타입 섞여 있을 때 
list2=[1,2,'test']
arr2=np.array(list2)

In [13]:
arr2.dtype

dtype('<U11')

In [14]:
arr2 # 크기가 큰 string으로 전부 변경됌

array(['1', '2', 'test'], dtype='<U11')

In [15]:
list3=[1,2,3.0]
arr3= np.array(list3)

In [16]:
arr3 # 크기가 큰 float64로 변경

array([1., 2., 3.])

In [17]:
arr3.dtype

dtype('float64')

### astype()
- ndarray내 데이터값의 변경

In [19]:
intarr=np.array([1,2,3])

In [20]:
floatarr=intarr.astype('float64')

In [23]:
floatarr,floatarr.dtype # 소수점들이 생긴거 볼 수 있음

(array([1., 2., 3.]), dtype('float64'))

### arange() , zeros(), ones()
- test용 데이터 , 대규모 데이터를 일괄 초기화 해야하는 경우
- arange() : array를 range로 표현
- zeros() : tuple형태의 shape 입력하면 모든 값을 0으로 채운 해당 shape가진 ndarray 반환
- ones() : 1로 채워짐 , zeros()와 유사

In [28]:
sarr=np.arange(10)

In [25]:
sarr, sarr.dtype , sarr.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'), (10,))

In [26]:
zeroarr=np.zeros((3,2), dtype='int32')
zeroarr

array([[0, 0],
       [0, 0],
       [0, 0]])

In [27]:
zeroarr.shape

(3, 2)

In [29]:
onearr=np.ones((3,2))
onearr, onearr.shape

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 (3, 2))

## reshape()
- ndarray의 차원과 크기 변경
- 맞지 않는 사이즈로 변경할 시에는 오류 반환
- 인자에 -1부여하면 알아서 새로운 shape로 변환해줌

In [34]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr2=arr1.reshape(2,5)

In [32]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
arr3=arr1.reshape(5,2)
arr3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [37]:
arr2=arr1.reshape(-1,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
arr2.shape

(2, 5)

In [38]:
arr3=arr1.reshape(5,-1)

In [39]:
arr3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
arr1=np.arange(8)
arr3d=arr1.reshape((2,2,2))

In [41]:
arr3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
arr3d.tolist() # ndarray-> tolist로 변경 

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

## Indexing
- 특정 데이터 추출
- Slicing : 연속된 arr의 ndarray 추출
- Fancy Indexing : list, ndarray로 인덱스 집합 지정하면 해당 위치에 해당하는 ndarray 반환
- Boolean Indexing :

#### 단일 값 추출

In [46]:
arr1=np.arange(start=1,stop=10)

In [44]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
value=arr1[2]

In [48]:
value, type(value)

(3, numpy.int32)

In [52]:
# 2차원 인덱싱
arr1d=np.arange(start=1, stop=10)
arr2d=arr1d.reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr2d[1,0]

4

#### Slicing

In [55]:
arr1=np.arange(start=1,stop=10)
arr3=arr1[0:3]
arr3

array([1, 2, 3])

In [56]:
# 2차원 접근 => r,c에 각각 indexing
arr1=np.arange(start=1,stop=10)
arr2=arr1.reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr2[0:2,0:2]

array([[1, 2],
       [4, 5]])

### Fancy Indexing

In [59]:
arr1=np.arange(start=1,stop=10)
arr2=arr1.reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr3=arr2[[0,1],2] # row측에 0,1을 col에 2를 적용 
r3=arr2[[0,1],2] # row측에 0,1을 col에 2를 적용 
# (0,2),(1,2)가 적용되어 3,6반환

In [61]:
arr3

array([3, 6])