# Pandas
## Titanic Data 가지고 Pandas 공부

In [2]:
import pandas as pd

### File 읽기
- read_csv() : 다양한 구분자에 대해 DataFrame으로 변환 가능 (default는 ',')
- read_table() : 구분자가 '\t' 
- read_fwf() : 고정 길이 기반의 칼럼 포맷

In [4]:
titanic=pd.read_csv(r'C:/Users/admin/dataset/train.csv')

In [5]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

## Shape
- DataFrame의 행과 열 알아보기
- titanic data는 891개의 row, 12개의 column으로 이루어짐

In [7]:
titanic.shape 

(891, 12)

## info() , describe()
- info() : data건수 , data type, null 건수
- describe() : column별 숫자형 데이터의 n-percentile 분포도, 평균값, 최댓값, 최소값  
            : 숫자형 column의 분포도만 조사 

In [8]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [9]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

## value_counts()
- 해당 column값의 유형과 건수 확인 가능
- 많은 건수 순서로 정렬되어 값을 반환

In [12]:
value_counts=titanic['Pclass'].value_counts()
value_counts

3    491
1    216
2    184
Name: Pclass, dtype: int64

### DataFrame의 []에 column입력하면 Series 객체 반환

In [14]:
tpclass=titanic['Pclass']
type(tpclass)

pandas.core.series.Series

## ndarray, List, Dictionary를 DataFrame으로 만들기

In [16]:
import numpy as np

### 1차원 데이터

In [23]:
colname=['col1']
list1=[1,2,3]
arr1=np.array(list1)

#### 1) ndarray => DataFrame

In [19]:
df1=pd.DataFrame(arr1,columns=colname)

In [20]:
df1

col1
0     1
1     2
2     3

#### 2) list -> DataFrame

In [21]:
df2=pd.DataFrame(list1,columns=colname)

In [22]:
df2

col1
0     1
1     2
2     3

### 2차원 데이터

In [25]:
colname2=['col1','col2','col3']

In [27]:
list2=[[1,2,3],[11,12,13]]
arr2=np.array(list2)

### 1) list -> DataFrame

In [28]:
df2=pd.DataFrame(list2,columns=colname2)

In [29]:
df2

col1  col2  col3
0     1     2     3
1    11    12    13

### 2) ndarray -> DataFrame

In [30]:
df3=pd.DataFrame(arr2,columns=colname2)

In [31]:
df3

col1  col2  col3
0     1     2     3
1    11    12    13

### 3) Dictionary -> DataFrame
- key : column명 
- value : column data로 입력

In [34]:
dictio={'col1':[1,11], 'col2': [2,22], 'col3':[3,33]}
df_dict=pd.DataFrame(dictio)

In [33]:
df_dict

col1  col2  col3
0     1     2     3
1    11    22    33

## DataFrame을 ndarray, list, dictionary로 변환

### 1) DataFrame -> ndarray 

In [36]:
arr3=df_dict.values

In [37]:
arr3

array([[ 1,  2,  3],
       [11, 22, 33]], dtype=int64)

### 2) DataFrame -> list

In [39]:
list3=df_dict.values.tolist()
list3

[[1, 2, 3], [11, 22, 33]]

### 3) DataFrame -> Dictionary

In [40]:
dict3=df_dict.to_dict('list')
# 딕셔너리 값이 list형으로 반환됌
dict3

{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

## DataFrame의 column dataset 생성 & 수정

In [41]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

### 새로운 column 추가

In [44]:
titanic['Age_0']=0

In [43]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0  
3      0            113803  53.1000  C123        S      0  
4      0            373450   8.0500   NaN        S      0

In [46]:
titanic['age_10']=titanic['Age']*10
titanic['Family_no']=titanic['SibSp']+titanic['Parch']+1
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  age_10  Family_no  
0      0         A/5 21171   7.2500   NaN        S      0   220.0          2  
1      0          PC 17599  71.2833   C85        C      0   380.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      0   260.0          1

### 기존 column값 update

In [47]:
titanic['age_10']=titanic['age_10']+100

In [48]:
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  age_10  Family_no  
0      0         A/5 21171   7.2500   NaN        S      0   320.0          2  
1      0          PC 17599  71.2833   C85        C      0   480.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      0   360.0          1

## Drop(labels=None, axis=0, columns=None, level=None, inplace=False, errors='raise')
- data 삭제
- labels : axis에 따라 달라짐 ( 가리키는 row, col )
- axis
    - axis=0 : row 방향 축 (->) (보통 이상치 데이터 삭제하는 경우에 사용)
    - axis=1 : columns 방향 축 (column을 drop함)
- inplace
    - inplace=True : 자신의 DataFrame의 값을 삭제

### column삭제

In [50]:
titanic_drop=titanic.drop('Age_0',axis=1)

In [52]:
titanic_drop.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  age_10  Family_no  
0      0  A/5 21171   7.2500   NaN        S   320.0          2  
1      0   PC 17599  71.2833   C85        C   480.0          2

In [54]:
drop_result=titanic.drop(['Age_0','age_10', 'Family_no'],axis=1, inplace=True)
titanic.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

### row삭제하기


In [55]:
titanic.drop([0,1,2],axis=0,inplace=True)

In [56]:
titanic.head(3)

PassengerId  Survived  Pclass  \
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   
5                              Moran, Mr. James    male   NaN      0      0   

   Ticket     Fare Cabin Embarked  
3  113803  53.1000  C123        S  
4  373450   8.0500   NaN        S  
5  330877   8.4583   NaN        Q

## Index 객체 추출
- DataFrame.index , Series.index
- index 객체는 식별성 데이터를 1차원 array로 가짐
- 한번 만들어진 index 객체는 변경 불가
- 연산에서 제외 (식별용)


In [68]:
titanic=pd.read_csv(r'C:/Users/admin/dataset/train.csv')

In [58]:
titanic.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [59]:
#index 객체 추출
indexes=titanic.index

In [60]:
indexes

RangeIndex(start=0, stop=891, step=1)

In [62]:
# index객체를 array로 변경
indexes.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [66]:
indexes[:5].values

array([0, 1, 2, 3, 4], dtype=int64)

In [67]:
indexes.values[:5]

array([0, 1, 2, 3, 4], dtype=int64)

In [69]:
# 연산에 포함되지 않음
series_fair=titanic['Fare']
series_fair.max()

512.3292

In [70]:
series_fair.sum()

28693.9493

## reset_index()
- 새롭게 index를 연속 숫자 형으로 할당
- 기존 index는 'index'라는 column명으로 추가됌
- Series에 reset_index() 적용하면 Series 아님 DataFrame이 반환
- drop=True 설정하면 기존 인덱스는 추가되지 X

In [74]:
titanic_reset=titanic.reset_index(inplace=False)

In [73]:
titanic_reset.head()

index  PassengerId  Survived  Pclass  \
0      0            1         0       3   
1      1            2         1       1   
2      2            3         1       3   
3      3            4         1       1   
4      4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [75]:
value_counts=titanic['Pclass'].value_counts()
value_counts # 많은 순서대로 정렬되서 나옴

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [82]:
new_value_counts=value_counts.reset_index(inplace=False)

In [83]:
new_value_counts #dataframe이 됌

index  Pclass
0      3     491
1      1     216
2      2     184

In [84]:
type(new_value_counts)

pandas.core.frame.DataFrame

In [86]:
new_value_counts1=value_counts.reset_index(inplace=False, drop=True)
new_value_counts1 # 그대로 Series

0    491
1    216
2    184
Name: Pclass, dtype: int64